# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=generic
endif
export config

PROJECTS := optproject

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

optproject: 
	@echo "==== Building optproject ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   generic"
	@echo "   debug"
	@echo "   server"
	@echo "   mymachine"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   optproject"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
